apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ms-one.local.info
    http:
      paths:
      - path: /
        backend:
          serviceName: ms-one-service
          servicePort: 80
  - host: ms-two.local.info
    http:
      paths:
      - path: /
        backend:
          serviceName: ms-two-service
          servicePort: 80
