apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-one-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-one
  template:
    metadata:
      labels:
        app: ms-one
    spec:
      containers:
      - name: ms-one-container
        image: ms-one:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
