apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-two-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-two
  template:
    metadata:
      labels:
        app: ms-two
    spec:
      containers:
      - name: ms-two-container
        image: ms-two:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: ms-two-secrets
              optional: false
          - configMapRef:
              name: ms-two-configs
              optional: false

